# Note: It requires docker-compose 1.13.0
#
# Usage: docker-compose up -d
version: "3"

services:
  # Selenium hub
  selenium_hub:
    image: selenium/hub:3.14.0-curium
    ports:
      - 4444:4444

  # Docker-Android for Android application testing
  nexus_7.0:
    image: budtmo/docker-android-x86-7.0
    privileged: true
    scale: 1
    depends_on:
      - selenium_hub
    ports:
      - 6080:6080
    volumes:
      - $PWD/src/resources/apps/android/app-preproduction-jobget-14-jan.apk:/root/tmp/app-preproduction-jobget-14-jan.apk
      - ./video-nexus_7.0:/tmp/video
    environment:
      - DEVICE=Nexus 5
      - CONNECT_TO_GRID=true
      - APPIUM=true
      - SELENIUM_HOST=selenium_hub
      - AUTO_RECORD=true
